#!/bin/bash
# Pulls per-color mockup images from Printful API for all products.
# Saves one image per design x type x color to public/images/designs/{slug}/
# Generates src/data/mockup-images.ts with the image map.

set -euo pipefail
cd "$(dirname "$0")/.."

export $(grep PRINTFUL_API_KEY .env | xargs)

if [ -z "${PRINTFUL_API_KEY:-}" ]; then
  echo "ERROR: PRINTFUL_API_KEY not loaded from .env"
  exit 1
fi

echo "Printful API key loaded: ${PRINTFUL_API_KEY:0:10}..."

# Map Printful product name prefixes to design slugs
# Format: printful_prefix:slug:type
PRODUCT_MAP=(
  "bbc_beer_tee:bear-valley-crest:tee"
  "bbc_beer_longsleeve:bear-valley-crest:long_sleeve"
  "bbc_beer_hoodie:bear-valley-crest:hoodie"
  "foxfarm_beer_tee:pine-ridge-sunset:tee"
  "foxfarm_beer_longsleeve:pine-ridge-sunset:long_sleeve"
  "foxfarm_beer_hoodie:pine-ridge-sunset:hoodie"
  "bear_liberty_tee:woodland-original:tee"
  "bear_liberty_longsleeve:woodland-original:long_sleeve"
  "bear_liberty_hoodie:woodland-original:hoodie"
  "moonridge_both_mountains_tee:moonridge-both-mountains:tee"
  "moonridge_both_mountains_longsleeve:moonridge-both-mountains:long_sleeve"
  "moonridge_both_mountains_hoodie:moonridge-both-mountains:hoodie"
  "fawnskin_beer_tee:fawnskin-beer:tee"
  "fawnskin_beer_longsleeve:fawnskin-beer:long_sleeve"
  "fawnskin_beer_hoodie:fawnskin-beer:hoodie"
)

# Get all products
echo "Fetching product list..."
PRODUCTS=$(curl -s https://api.printful.com/store/products \
  -H "Authorization: Bearer $PRINTFUL_API_KEY")

# Collect all image entries for the TS map
declare -a TS_ENTRIES=()

for mapping in "${PRODUCT_MAP[@]}"; do
  IFS=':' read -r printful_name slug product_type <<< "$mapping"

  # Find product ID by name
  PRODUCT_ID=$(echo "$PRODUCTS" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for p in data['result']:
    if p['name'] == '$printful_name':
        print(p['id'])
        break
" 2>/dev/null || true)

  if [ -z "$PRODUCT_ID" ]; then
    echo "  WARN: No product found for $printful_name — skipping"
    continue
  fi

  echo "Processing $slug / $product_type (product $PRODUCT_ID)..."

  # Create output directory
  mkdir -p "public/images/designs/$slug"

  # Get variants and extract unique color preview URLs
  VARIANTS=$(curl -s "https://api.printful.com/store/products/$PRODUCT_ID" \
    -H "Authorization: Bearer $PRINTFUL_API_KEY")

  # Extract unique color + preview URL pairs, download images
  echo "$VARIANTS" | python3 -c "
import json, sys
data = json.load(sys.stdin)
seen = set()
for v in data['result']['sync_variants']:
    parts = v['name'].split(' / ')
    if len(parts) >= 2:
        color = parts[1]
    else:
        continue
    if color in seen:
        continue
    seen.add(color)
    preview = next((f.get('preview_url','') for f in v.get('files',[]) if f['type']=='preview'), '')
    if preview:
        # Normalize color for filename
        norm = color.lower().replace(' ', '-')
        print(f'{color}|{norm}|{preview}')
" | while IFS='|' read -r color norm_color url; do
    OUTFILE="public/images/designs/$slug/${product_type}-${norm_color}.png"
    if [ -f "$OUTFILE" ]; then
      echo "  Exists: $OUTFILE"
    else
      echo "  Downloading: $slug/${product_type}-${norm_color}.png"
      curl -sL "$url" -o "$OUTFILE"
    fi
    # Collect TS entry
    echo "  \"${slug}/${product_type}-${norm_color}\": \"/images/designs/${slug}/${product_type}-${norm_color}.png\"," >> /tmp/mockup-entries.txt
  done

  # Small delay to avoid rate limiting
  sleep 0.2
done

# Generate TypeScript map
echo ""
echo "Generating src/data/mockup-images.ts..."

cat > src/data/mockup-images.ts << 'HEADER'
/**
 * Maps design/type/color combinations to mockup image paths.
 * Key format: {designSlug}/{productType}-{normalizedColor}
 * Generated by scripts/pull-mockup-images.sh from Printful API.
 */
export const MOCKUP_IMAGES: Record<string, string> = {
HEADER

sort /tmp/mockup-entries.txt | uniq >> src/data/mockup-images.ts
echo "};" >> src/data/mockup-images.ts

rm -f /tmp/mockup-entries.txt

# Count results
TOTAL=$(grep -c '":' src/data/mockup-images.ts)
echo "Done! $TOTAL mockup images mapped."
